import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { TextField, Button} from "@mui/material";

import * as React from 'react';
import { FormControl, useFormControlContext } from '@mui/base/FormControl';
import { Input, inputClasses } from '@mui/base/Input';
import { styled } from '@mui/system';

import clsx from 'clsx';
type SubmitProps = {
	description: string
}

export function Submit(props: SubmitProps) {
	const styles = {
		form: {
		  display: "flex",
		  flexDirection: "column",
		  maxWidth: "700px", // Adjust the maximum width as needed
		  margin: "0 auto",
		  marginTop: "40px",
		},
		textField: {
		  marginBottom: "36px", // Adjust the spacing between fields as needed
		},
		submitButton: {
		  marginTop: "16px", // Adjust the spacing above the submit button as needed
		  backgroundColor: "#6A0DAD", // Byzantine Blue
		  color: "white",
		},
		newButton: {
			backgroundColor: "#EE4B2B",
  border: "none",
  color: "white",
  padding: "16px 32px",
  textDecoration: "none",
  margin: "4px 2px",
  cursor: "pointer",
  fontWeight: 'bold'
		}
	  }

	  return (
		<div className="description-form">
		  <div>
			<Button
			  
			  style={styles.newButton}
			  disabled={false}
			  onClick={() => console.log("i read", props.description)}
			>
			  {"Submit"}
			</Button>
		  </div>
		</div>
	  );
	}
//   }

export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	return (
		<>
			<Head>
				<title>WalletConnect | Next Starter Template</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<div
					className={styles.backdrop}
					style={{
						opacity:
							isConnectHighlighted || isNetworkSwitchHighlighted
								? 1
								: 0,
					}}
				/>
				<div className={styles.header}>
					<div className={styles.logo}>
						<Image
							src="/logo.svg"
							alt="WalletConnect Logo"
							height="32"
							width="203"
						/>
					</div>
					<div className={styles.buttons}>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isNetworkSwitchHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-network-button />
						</div>
						<div
							onClick={closeAll}
							className={`${styles.highlight} ${
								isConnectHighlighted
									? styles.highlightSelected
									: ``
							}`}
						>
							<w3m-button />
						</div>
					</div>
				</div>
			</header>
			<main className={styles.main}>
				<div className={styles.wrapper}>
					<div className={styles.container}>
						<h1>Smart Post Marketing</h1>
						<div className={styles.content}>
						<BasicFormControl></BasicFormControl>
						</div>
					</div>
					<div className={styles.footer}>
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							strokeWidth={1.5}
							stroke="currentColor"
							height={16}
							width={16}
						>
							<path
								strokeLinecap="round"
								strokeLinejoin="round"
								d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z"
							/>
						</svg>
						<a
							href="https://docs.walletconnect.com/web3modal/react/about?utm_source=next-starter-template&utm_medium=github&utm_campaign=next-starter-template"
							target="_blank"
						>
							Check out the full documentation here
						</a>
					</div>
				</div>
			</main>
		</>
	);
}






function BasicFormControl() {
	const styles = {
		form: {
		  display: "flex",
		  flexDirection: "column",
		  maxWidth: "700px", // Adjust the maximum width as needed
		  margin: "0 auto",
		  marginTop: "40px",
		},
		textField: {
		  marginBottom: "36px", // Adjust the spacing between fields as needed
		},
		submitButton: {
		  marginTop: "16px", // Adjust the spacing above the submit button as needed
		  backgroundColor: "#6A0DAD", // Byzantine Blue
		  color: "white",
		},
	  };
	const [formData, setFormData] = useState({
		description: ""
	  });	
	  const handleSubmit = (e:any) => {
		e.preventDefault();
		// Handle form submission here This is where etherjs
		console.log(formData);
		setAlertSuccess(true);
	  };
	
	  const handleChange = (e:any) => {
		const { name, value } = e.target;
		setFormData({ ...formData, [name]: value });
	  };
	
	  const [alertSuccess, setAlertSuccess] = useState(false);
  return (
    <div className="research-form" 	>
        <h1>Please enter your company's description for our AI</h1>
          <br/>
          <br/>
        <form onSubmit={handleSubmit} >
            <TextField
                label="Company Description"
                name="description"
                fullWidth
                required
                onChange={handleChange}
                value={formData.description}
                InputLabelProps={{
                style: { color: 'white', fontWeight: 'bold' },
                }}
                InputProps={{
                style: { color: 'white', backgroundColor: '#7a8484', fontWeight: 'bold' },
                }}
            />
			<Submit description={formData.description}></Submit>
          {/* <CreatePeerReview feedback={formData.feedback} documentUrl={formData.documentUrl} rating={formData.rating} researchId={formData.researchId}/> */}
        </form>
		</div>
  );
}

